# Generated by Django 5.1.11 on 2025-06-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour_operator', '0006_alter_package_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adults_no', models.DecimalField(decimal_places=0, max_digits=3)),
                ('child_no', models.DecimalField(decimal_places=0, max_digits=3)),
                ('nights_no', models.DecimalField(decimal_places=0, max_digits=3)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_chosen', models.DateField()),
                ('resolved', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour_operator.package')),
            ],
        ),
    ]
