# Generated by Django 5.1.11 on 2025-07-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_quote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
