# Generated by Django 5.1.11 on 2025-07-05 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_quote_slug'),
        ('tour_operator', '0006_alter_package_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='package',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='tour_operator.package'),
        ),
    ]
