# Generated by Django 5.1.11 on 2025-06-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_operator', '0002_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
