# Generated by Django 5.1.11 on 2025-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_operator', '0003_alter_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
