# Generated by Django 5.1.11 on 2025-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_operator', '0004_package_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(),
        ),
    ]
