# Generated by Django 5.1.11 on 2025-06-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_operator', '0005_alter_package_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
